# Generated by Django 5.0.14 on 2025-10-14 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade_total', models.FloatField(default=0)),
                ('unidade_base', models.CharField(choices=[('g', 'Grama'), ('ml', 'Mililitro'), ('un', 'Unidade')], default='un', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='DEFAULT123', max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('data_fabricacao', models.DateField()),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('quantidade', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rc', models.CharField(max_length=20, unique=True, verbose_name='Registro de Colaborador')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=10)),
                ('funcao', models.CharField(max_length=50)),
                ('CPF_RG', models.CharField(max_length=20, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='colaboradores/')),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('bairro', models.CharField(blank=True, max_length=50, null=True)),
                ('cidade', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('complemento', models.CharField(blank=True, max_length=50, null=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaborador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FichaProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
                ('data_fabricacao', models.DateField()),
                ('textura', models.CharField(blank=True, max_length=255, null=True)),
                ('validade', models.PositiveIntegerField(default=3)),
                ('armazenamento', models.CharField(blank=True, max_length=255, null=True)),
                ('calorias', models.PositiveIntegerField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('tempo_preparo', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tempo de Preparo (minutos)')),
                ('perda_aceitavel', models.CharField(blank=True, max_length=50, verbose_name='Perda Aceitável')),
                ('rendimento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rendimento')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('assinado_por', models.CharField(blank=True, max_length=150, null=True)),
                ('data_assinatura', models.DateTimeField(blank=True, null=True)),
                ('peso_produto', models.FloatField(default=0, help_text='Peso do produto em gramas')),
                ('colaborador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='FichaInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_usada', models.FloatField()),
                ('unidade', models.CharField(choices=[('g', 'Grama'), ('ml', 'Mililitro'), ('un', 'Unidade')], max_length=10)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_insumos', to='core.fichaproducao')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.insumo')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoPronto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField(default=0)),
                ('data_fabricacao', models.DateField()),
                ('data_validade', models.DateField()),
                ('peso_produto', models.FloatField(default=0)),
                ('catalogo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='core.catalogoproduto')),
            ],
        ),
        migrations.AddField(
            model_name='fichaproducao',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produtopronto'),
        ),
        migrations.CreateModel(
            name='SaidaInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField()),
                ('unidade', models.CharField(choices=[('kg', 'Quilo(s)'), ('g', 'Grama(s)'), ('l', 'Litro(s)'), ('ml', 'Mililitro(s)'), ('un', 'Unidade(s)')], default='un', max_length=5)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('colaborador_entregando', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='core.colaborador')),
                ('colaborador_retira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retiradas', to='core.colaborador')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.insumo')),
            ],
        ),
    ]
