# Generated by Django 5.0.14 on 2025-10-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saidainsumo',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='saidainsumo',
            name='quantidade_complementar',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='saidainsumo',
            name='quantidade_principal',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='saidainsumo',
            name='unidade',
            field=models.CharField(choices=[('g', 'Grama(s)'), ('ml', 'Mililitro(s)'), ('un', 'Unidade(s)')], default='un', max_length=5),
        ),
    ]
