# Generated by Django 5.0.14 on 2025-10-17 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_saidainsumo_quantidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VistoriaInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_retirada', models.FloatField(default=0)),
                ('quantidade_usada', models.FloatField(default=0)),
                ('quantidade_teorica', models.FloatField(default=0)),
                ('quantidade_real', models.FloatField(default=0)),
                ('desperdicio', models.FloatField(default=0)),
                ('data_vistoria', models.DateField(auto_now_add=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.insumo')),
            ],
        ),
    ]
