# Generated by Django 5.2.7 on 2026-02-28 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_vistoriainsumo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.catalogoproduto')),
            ],
        ),
    ]
