# Generated by Django 5.2.7 on 2026-03-04 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='catalogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='core.catalogoproduto'),
        ),
    ]
