# Generated by Django 5.2.7 on 2026-03-04 20:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_produto_pedido_produto_venda_pedido_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtovenda',
            name='catalogo',
        ),
        migrations.AddField(
            model_name='produtovenda',
            name='codigo_externo',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
