# Generated by Django 5.2.7 on 2026-03-04 20:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_produtovenda_catalogo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtovenda',
            name='codigo_externo',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
