# Generated by Django 5.2.7 on 2026-03-07 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_produtovenda_codigo_externo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtovenda',
            name='produto_pronto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='core.produtopronto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produtovenda',
            name='codigo_externo',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='VistoriaInsumo',
        ),
    ]
