# Generated by Django 5.2.7 on 2026-03-08 18:29

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_produtovenda_produto_pronto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.CharField(default=core.models.gerar_codigo, max_length=20, unique=True),
        ),
    ]
