# Generated by Django 5.0.14 on 2026-04-02 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_produto_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='VistoriaInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_real', models.FloatField()),
                ('data_vistoria', models.DateField(auto_now_add=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.insumo')),
            ],
        ),
    ]
