# Generated by Django 5.0.14 on 2026-04-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_vistoriainsumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vistoriainsumo',
            name='desperdicio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='vistoriainsumo',
            name='quantidade_retirada',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='vistoriainsumo',
            name='quantidade_teorica',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='vistoriainsumo',
            name='quantidade_usada',
            field=models.FloatField(default=0),
        ),
    ]
