# Generated by Django 5.2.7 on 2026-04-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_vistoriainsumo_desperdicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
