# Generated by Django 5.2.7 on 2026-04-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_colaborador_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtopronto',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
